### ISSUE TITLE
Database link not working 

### ISSUE THREAD

**Issue by DaliJarboui** [LeeYiFang/Carkinos#6]
Database link not working ???????

**Comment by LeeYiFang** [comment]
Hi, Sorry for the inconvenience.
Please use the link below:
http://cellexpress.cgm.ntu.edu.tw/

Thank you

Best,
Yi-Fang Lee

DaliJarboui <notifications@github.com>於 2018年10月23日 週二，上午2:22寫道：

**Comment by DaliJarboui** [comment]
thanks for the fast reply however the link still not working.
have to mention that I m connecting from germany. 
the last available cached version of your link is from 6 Oct 2018 05:25:10 GM. 
regards

**Comment by LeeYiFang** [comment]
I have tried to connect the website from the U.S and it works. By the way,
I just received someone's mail from Germany these days, and they are using
the website, too. so I am not so sure about the issue you met. Can you
please show me the error you met and how you check the cached version? so
we can fix it asap

thanks

DaliJarboui <notifications@github.com>於 2018年10月23日 週二，上午5:02寫道：

**Comment by DaliJarboui** [comment]
thanks a lot, 
the link worked today I guess was a problem with the connection.

thanks again.
